CSV_path: "/hpc/ash252/Eryn/new_data/manual_labels/2025/napier_preseason/napier_pre-season_vs_GBHS_firstXV CSV.csv"
XML_path: "/hpc/ash252/Eryn/new_data/img_xml/2025/napier_preseason/gbhs-firstXV-napier_preseason-2025-filtered_5.0.xml"
schedule_path: "/hpc/ash252/Eryn/new_data/2025_session_record_human_final.xlsx"
Alignment_threshold: 5.0
PLA_threshold: 4
